# Generated by Django 5.0.7 on 2025-01-04 05:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0003_alter_doctor_qualification'),
        ('User', '0002_rename_name_newuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('problem_organ', models.CharField(max_length=10)),
                ('problem_description', models.TextField()),
                ('time_batch', models.CharField(max_length=6)),
                ('appointment_date', models.DateField(default=datetime.date.today)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.newuser')),
            ],
        ),
    ]
