# Generated by Django 5.0.7 on 2025-01-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_batch',
            field=models.CharField(max_length=7),
        ),
    ]
