# Generated by Django 5.0.7 on 2025-01-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='name',
            new_name='username',
        ),
    ]
