# Generated by Django 5.0.7 on 2025-01-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
